//! Linguist exclusion globs for the language-detection walk.
//!
//! # Provenance
//!
//! Ported from `hyperpolyglot` 0.1.7 (`src/filters/vendor.rs` and
//! `src/filters/documentation.rs`, MIT), which in turn carries the glob lists
//! from `github/linguist`'s `vendor.yml` (also MIT). Both licences are
//! reproduced by their upstream projects; this file is a data port, not a code
//! port -- only the glob strings and their grouping comments were copied.
//!
//! # Why the lists exist
//!
//! GPY replaced `hyperpolyglot` with `gengo-language` in #523, and with it the
//! walk that `hyperpolyglot::get_language_breakdown` used to own. That walk was
//! never a bare [`ignore::WalkBuilder`]: it layered these exclusions through an
//! [`OverrideBuilder`] first. Keeping them is parity, not tidiness. Without
//! them the walk visits a strictly larger file set, and
//! `confidence_for`'s denominator is the total across *every* detected
//! language -- `normalize_language_name` passes unrecognized names through
//! unchanged, so `Markdown` and `JSON` land in the aggregate too. Dropping the
//! lists therefore moves every reported confidence ratio, not just the ones
//! for vendored code.

use ignore::overrides::{Override, OverrideBuilder};
use std::path::Path;

/// Vendored-code exclusions: bundled dependencies, generated build scaffolding,
/// and the third-party `JavaScript` that linguist treats as not-your-code.
const VENDOR_GLOBS: &[&str] = &[
    // Caches
    "!**/cache/**",
    // Dependencies
    "!**/[Dd]ependencies/**",
    // Distributions
    "!**/dist/**",
    // C deps
    "!**/deps/**",
    "!**/configure",
    "!**/config.guess",
    "!**/config.sub",
    // stuff autogenerated by autoconf - still C deps
    "!**/aclocal.m4",
    "!**/libtool.m4",
    "!**/ltoptions.m4",
    "!**/ltsugar.m4",
    "!**/ltversion.m4",
    "!**/lt~obsolete.m4",
    // .NET Core Install Scripts
    "!**/dotnet-install.ps1",
    "!**/dotnet-install.sh",
    // Linters
    "!**/cpplint.py",
    // Node dependencies
    "!**/node_modules/**",
    // Yarn releases
    "!**/.yarn/releases/**",
    // esy.sh dependencies
    "!**/_esy",
    // Bower Components
    "!**/bower_components/**",
    // Erlang bundles
    "!**/rebar/**",
    "!**/erlang.mk",
    // Go dependencies
    "!**/Godeps/_workspace/**",
    // Go fixtures
    "!**/testdata/**",
    // GNU indent profiles
    "!**/.indent.pro",
    // Minified JavaScript and CSS
    "!**/*[.-]min.{css,js}",
    // Stylesheets imported from packages
    "!**/*import.{css,less,scss,styl}",
    // Bootstrap css and js
    "!**/bootstrap*.{js,css,less,scss,styl}",
    "!**/custom.bootstrap*.{js,css,less,scss,styl}",
    // Font Awesome
    "!**/font*awesome.{js,css,less,scss,styl}",
    "!**/font*awesome/**/*.{js,css,less,scss,styl}",
    // Foundation css
    "!**/foundation.{css,less,scss,styl}",
    // Normalize.css
    "!**/normalize.{css,less,scss,styl}",
    // Skeleton.css
    "!**/skeleton.{css,less,scss,styl}",
    // Bourbon css
    "!**/[Bb]ourbon.{css,less,scss,styl}",
    // Animate.css
    "!**/animate.{css,less,scss,styl}",
    // Materialize.css
    "!**/materialize.{css,less,scss,styl,js}",
    // Select2
    "!**/select2/*.{css,scss,js}",
    // Bulma css
    "!**/bulma.{css,sass,scss}",
    // Vendored dependencies
    "!**/{3rd,[Tt]hird}*[Pp]arty/**",
    "!**/vendor/**",
    "!**/vendors/**",
    "!**/external/**",
    "!**/extern/**",
    "!**/[Vv]endor/**",
    // Debian packaging
    "!**/debian/**",
    // Haxelib projects often contain a neko bytecode file named run.n
    "!**/run.n",
    // Bootstrap Datepicker
    "!**/bootstrap-datepicker/**",
    /* Commonly Bundled JavaScript frameworks */
    // jQuery
    "!**/jquery*.{js,css}",
    // Fuel UX
    "!**/fuelux.js",
    // bootboxjs
    "!**/bootbox.js",
    // pdf-worker
    "!**/pdf.worker.js",
    // Slick
    "!**/slick.*.js",
    // Leaflet plugins
    "!**/Leaflet.Coordinates*.src.js",
    "!**/leaflet.draw-src.js",
    "!**/leaflet.draw.css",
    "!**/Control.FullScreen.{css,js}",
    "!**/leaflet.spin.js",
    "!**/wicket-leaflet.js",
    // Sublime Text workspace files
    "!**/.sublime-project",
    "!**/.sublime-workspace",
    // VS Code workspace files
    "!**/.vscode",
    // Prototype
    "!**/prototype*.js",
    "!**/effects.js",
    "!**/controls.js",
    "!**/dragdrop.js",
    // Typescript definition files
    "!**/*.d.ts",
    // MooTools
    "!**/mootools*.js",
    // Dojo
    "!**/dojo.js",
    // MochiKit
    "!**/MochiKit.js",
    // YUI
    "!**/yahoo-*.js",
    "!**/yui*.js",
    // WYS editors
    "!**/ckeditor.js",
    "!**/tiny_mce*.js",
    "!**/tiny_mce/{langs,plugins,themes,utils}/**",
    // Ace Editor
    "!**/ace-build/**",
    // Fontello CSS files
    "!**/fontello*.css",
    // MathJax
    "!**/MathJax/**",
    // Chart.js
    "!**/Chart.js",
    // CodeMirror
    "!**/[Cc]ode[Mm]irror/*{lib,mode,theme,addon,keymap,demo}/**",
    // SyntaxHighlighter - http://alexgorbatchev.com/
    "!**/shBrush*.js",
    "!**/shCore.js",
    "!**/shLegacy.js",
    // AngularJS
    "!**/angular*.js",
    // D3.js
    "!**/d3*.js",
    // React
    "!**/react*.js",
    // flow-typed
    "!**/flow-typed/*.js",
    // Modernizr
    "!**/modernizr*.js",
    // Knockout
    "!**/knockout-*.js",
    /* Python */
    // Sphinx
    "!**/{doc,docs}/{build,themes,theme,templates,template,static}",
    // django
    "!**/admin_media/**",
    "!**/env/**",
    // Fabric
    "!**/fabfile.py",
    // WAF
    "!**/waf",
    // .osx
    "!**/.osx",
    /* Obj-C */
    // Xcode
    "!**/.xctemplate/**",
    "!**/.imageset/**",
    // Carthage
    "!**/Carthage/**",
    // Sparkle
    "!**/Sparkle/**",
    // Crashlytics
    "!**/Crashlytics.framework/**",
    // Fabric
    "!**/Fabric.framework/**",
    // BuddyBuild
    "!**/BuddyBuildSDK.framework/**",
    // Realm
    "!**/Realm.framework",
    // RealmSwift
    "!**/RealmSwift.framework",
    // git config files
    "!**/.gitattributes",
    "!**/.gitignore",
    "!**/.gitmodules",
    /* Groovy */
    // Gradle
    "!**/gradlew",
    "!**/gradlew.bat",
    "!**/gradle/wrapper/**",
    /* Java */
    // Maven
    "!**/mvnw",
    "!**/mvnw.cmd",
    "!**/.mvn/wrapper/**",
    /* .NET */
    // Visual Studio IntelliSense
    "!**/*-vsdoc.js",
    "!**/*.intellisense.js",
    // jQuery validation plugin (MS bundles this with asp.net mvc)
    "!**/jquery*.validate*.js",
    "!**/jquery*.unobtrusive-ajax.js.js",
    // Microsoft Ajax
    "!**/[Mm]icrosoft{[Aa]jax,[Vv]alidation}*.js",
    // NuGet
    "!**/[Pp]ackages/*.*/**",
    // ExtJS
    "!**/extjs/*.{js,xml,txt,html,properties}",
    "!**/extjs/{.sencha,docs,builds,cmd,examples,locale,packages,plugins,resources,src,welcome}/**",
    // Html5shiv
    "!**/html5shiv.js",
    // Test fixtures
    "!**/[Tt]es{t,ts}/fixtures/**",
    "!**/[Ss]pe{c,cs}/fixtures/**",
    // PhoneGap/Cordova
    "!**/cordova*.js",
    // Foundation js
    "!**/foundation*.js",
    // Vagrant
    "!**/Vagrantfile",
    // .DS_Stores
    "!**/.[Dd][Ss]_[Ss]tore",
    // R packages
    "!**/vignettes/**",
    "!**/inst/extdata/**",
    // Octicons
    "!**/octicons.css",
    "!**/sprockets-octicons.scss",
    // Typesafe Activator
    "!**/activiator",
    "!**/activator.bat",
    // ProGuard
    "!**/proguard.pro",
    "!**/proguard-rules.pro",
    // PuPHPet
    "!**/puphet/**",
    // Android Google APIs
    "!**/.google_apis/**",
    // Jenkins Pipeline
    "!**/Jenkinsfile",
];

/// Documentation exclusions: doc directories, sample trees, and the standard
/// top-level prose files.
const DOCUMENTATION_GLOBS: &[&str] = &[
    // Documentation directories
    "!**/[Dd]ocs/**",
    "!**/[Dd]oc/**",
    "!**/[Dd]ocumentation/**",
    "!**/[Gg]roovydoc/**",
    "!**/[Jj]avadoc/**",
    "!**/[Mm]an/**",
    "!**/[Ee]xamples/**",
    "!**/[Dd]emo/**",
    "!**/[Dd]emos/**",
    "!**/inst/doc/**",
    // Documentation files
    "!**/CHANGE*",
    "!**/CHANGES*",
    "!**/CHANGELOG*",
    "!**/CONTRIBUTING*",
    "!**/COPYING*",
    "!**/INSTALL*",
    "!**/LICEN[CS]E*",
    "!**/[Ll]icen[cs]e*",
    "!**/README*",
    "!**/[Rr]eadme*",
    // Samples folders
    "!**/[Ss]ample/**",
    "!**/[Ss]amples/**",
];

/// Builds the exclusion [`Override`] the detection walk applies, rooted at
/// `root`.
///
/// Every pattern is a compile-time constant validated by
/// `tests::every_glob_is_accepted`, so neither failure arm below is reachable
/// in practice. They exist because this runs inside a prompt daemon, where
/// degrading to an unfiltered walk beats aborting the process -- the same
/// choice the rest of `detector.rs` makes for unreadable directories.
pub(super) fn exclusion_overrides(root: &Path) -> Override {
    let mut builder = OverrideBuilder::new(root);
    for glob in DOCUMENTATION_GLOBS.iter().chain(VENDOR_GLOBS) {
        if builder.add(glob).is_err() {
            return Override::empty();
        }
    }
    builder.build().unwrap_or_else(|_| Override::empty())
}

#[cfg(test)]
mod tests {
    #![allow(clippy::missing_panics_doc)]

    use super::*;

    #[test]
    fn every_glob_is_accepted() {
        let mut builder = OverrideBuilder::new("./");
        for glob in DOCUMENTATION_GLOBS.iter().chain(VENDOR_GLOBS) {
            assert!(builder.add(glob).is_ok(), "malformed glob: {glob}");
        }
        assert!(builder.build().is_ok(), "override set must build");
    }

    #[test]
    fn vendored_and_documentation_paths_are_ignored() {
        let overrides = exclusion_overrides(Path::new("./"));
        for path in [
            "vendor/bundled.rs",
            "node_modules/pkg/index.js",
            "third_party/lib.c",
            "README.md",
            "docs/guide.md",
        ] {
            assert!(
                overrides.matched(path, false).is_ignore(),
                "{path} should be excluded"
            );
        }
    }

    #[test]
    fn ordinary_source_paths_are_not_ignored() {
        let overrides = exclusion_overrides(Path::new("./"));
        for path in ["src/main.rs", "lib/app.py", "cmd/server/main.go"] {
            assert!(
                overrides.matched(path, false).is_none(),
                "{path} should not be excluded"
            );
        }
    }
}
