#!/usr/bin/env zsh
# tests/zsh/segment_bg_export.test.zsh
# SPDX-License-Identifier: GPL-3.0-or-later
#
# #614: __gpy_segment_bg is generated by the agent's `theme export`
# (gpy-agent/src/theme/export.rs's append_segment_bg_function, built from
# SEGMENT_BG_VARS) instead of a hand-copied `case "$seg" in ... esac` table
# in zsh/core/init.zsh. This test sources a REAL export from the
# locally-built debug binary (not whatever `gpy-agent` happens to be
# installed on PATH, which may predate this change) and checks:
#   1. After sourcing, __gpy_segment_bg git returns $__color_git_clean_bg.
#   2. zsh/core/init.zsh and zsh/segments/*.zsh no longer hand-copy a
#      segment->bg case table (`case "$seg" in`).

ROOT=${0:a:h:h:h}
# Shared skip contract (#650): exits 0 locally, fails under CI.
emulate sh -c ". $ROOT/tests/lib/shell_e2e.sh"
cd "$ROOT"

FAILED=0
check() {
    local label=$1 expected=$2 actual=$3
    if [[ "$actual" == "$expected" ]]; then
        echo "PASS: $label"
    else
        echo "FAIL: $label (expected [$expected], got [$actual])"
        FAILED=1
    fi
}

AGENT_BIN="$ROOT/gpy-agent/target/debug/gpy-agent"
if [[ ! -x "$AGENT_BIN" ]]; then
    test_skip "$AGENT_BIN not built (run \`cargo build\` in gpy-agent first)"
fi

source zsh/core/constants.zsh
source zsh/core/ipc.zsh

export_output=$("$AGENT_BIN" theme export --format zsh 2>/dev/null)
if [[ -z "$export_output" ]]; then
    echo "FAIL: gpy-agent theme export --format zsh produced no output"
    exit 1
fi
eval "$export_output"

check "__gpy_segment_bg git matches \$__color_git_clean_bg" \
    "${__color_git_clean_bg:-}" "$(__gpy_segment_bg git)"

# Fork-free out-var calling convention (the render loop's hot path).
out_var_result=""
__gpy_segment_bg git out_var_result
check "__gpy_segment_bg git OUT_VAR writes the same value" \
    "${__color_git_clean_bg:-}" "$out_var_result"

check "unknown segment returns empty" "" "$(__gpy_segment_bg not-a-real-segment)"

# The hand-copied case table is gone from init.zsh and every segment file.
hit_count=$(grep -rl 'case "\$seg" in' zsh 2>/dev/null | wc -l | tr -d ' ')
check "no 'case \"\$seg\" in' table left under zsh/" 0 "$hit_count"

if [[ $FAILED -ne 0 ]]; then
    echo "=== FAILED ==="
    exit 1
fi
echo "=== segment_bg export test passed ==="
