#!/usr/bin/env bash
# tests/bash/install_hooks_prek.test.bash
#
# Regression test for #666: scripts/install-hooks.sh must leave a clone with
# prek shims for pre-commit, pre-push and commit-msg, even when Raven already
# symlinked its own hooks into .git/hooks (e.g. .git/hooks/pre-commit ->
# .raven/git-hooks/pre-commit).
#
# Real prek, given an existing hook, renames it to <hook>.legacy and keeps
# running it (migration mode), and with --force writes its shim through the
# symlink into the tracked .raven/git-hooks/pre-commit. The stub `prek` below reproduces the
# rename so the test needs no prek install; the script must remove Raven's
# symlinks first so neither outcome can happen.
#
# Without the fix: pre-commit/pre-push keep a .legacy Raven symlink and no
# commit-msg shim is installed.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_COMMON_DIR

FAILED=0
pass() { echo "PASS: $*"; }
fail() {
    echo "FAIL: $*"
    FAILED=1
}

SANDBOX="$(mktemp -d "${TMPDIR:-/tmp}/gpy-install-hooks.XXXXXX")"
trap 'rm -rf "$SANDBOX"' EXIT

REPO="$SANDBOX/repo"
mkdir -p "$REPO/scripts" "$REPO/.raven/git-hooks" "$SANDBOX/bin"
cp "$ROOT/scripts/install-hooks.sh" "$REPO/scripts/install-hooks.sh"
git -C "$REPO" init -q
for hook in pre-commit pre-push commit-msg; do
    printf '#!/bin/sh\necho raven-%s\n' "$hook" >"$REPO/.raven/git-hooks/$hook"
    chmod +x "$REPO/.raven/git-hooks/$hook"
    ln -s "../../.raven/git-hooks/$hook" "$REPO/.git/hooks/$hook"
done
cp -p "$REPO/.raven/git-hooks/pre-commit" "$SANDBOX/raven-pre-commit.orig"

# Stub prek: `install --hook-type T ...` mimics prek's migration mode (an
# existing hook is renamed to T.legacy), then writes a shim.
cat >"$SANDBOX/bin/prek" <<'EOF'
#!/usr/bin/env bash
cmd="$1"
shift
[ "$cmd" = install ] || exit 0
hooks="$(git rev-parse --git-path hooks)"
while [ $# -gt 0 ]; do
    if [ "$1" = --hook-type ]; then
        target="$hooks/$2"
        if [ -e "$target" ] || [ -L "$target" ]; then
            mv "$target" "$target.legacy"
        fi
        printf '#!/bin/sh\n# File generated by prek\n' >"$target"
        chmod +x "$target"
        shift
    fi
    shift
done
EOF
chmod +x "$SANDBOX/bin/prek"

output="$(cd "$REPO" && PATH="$SANDBOX/bin:$PATH" ./scripts/install-hooks.sh 2>&1)" ||
    fail "install-hooks.sh exited non-zero: $output"

for hook in pre-commit pre-push commit-msg; do
    path="$REPO/.git/hooks/$hook"
    if [ -f "$path" ] && [ ! -L "$path" ] && grep -q 'generated by prek' "$path"; then
        pass "$hook is a prek shim"
    else
        fail "$hook is not a prek shim: $(ls -l "$path" 2>&1)"
    fi
    if [ -e "$path.legacy" ] || [ -L "$path.legacy" ]; then
        fail "$hook.legacy remains, so Raven's hook would still run: $(ls -l "$path.legacy")"
    else
        pass "no $hook.legacy left behind"
    fi
done

if cmp -s "$REPO/.raven/git-hooks/pre-commit" "$SANDBOX/raven-pre-commit.orig"; then
    pass "tracked .raven/git-hooks/pre-commit is untouched"
else
    fail "tracked .raven/git-hooks/pre-commit was overwritten"
fi

if [ "$FAILED" -ne 0 ]; then
    echo "FAILED"
    exit 1
fi
echo "=== All install-hooks tests passed ==="
