name = "catppuccin-macchiato"
description = "Imported base scheme: Catppuccin Macchiato (dark)"

[colors]
black = "#494d64"
blue = "#8aadf4"
bright_black = "#5b6078"
bright_blue = "#7dc4e4"
bright_cyan = "#91d7e3"
bright_green = "#a6da95"
bright_magenta = "#f5bde6"
bright_red = "#ee99a0"
bright_white = "#b8c0e0"
bright_yellow = "#f4dbd6"
brown = "#f0c6c6"
cyan = "#8bd5ca"
green = "#a6da95"
magenta = "#c6a0f6"
orange = "#f5a97f"
red = "#ed8796"
white = "#a5adcb"
yellow = "#eed49f"
