name = "catppuccin-latte"
description = "Imported base scheme: Catppuccin Latte (light)"

[colors]
black = "#5c5f77"
blue = "#1e66f5"
bright_black = "#6c6f85"
bright_blue = "#209fb5"
bright_cyan = "#04a5e5"
bright_green = "#40a02b"
bright_magenta = "#ea76cb"
bright_red = "#e64553"
bright_white = "#bcc0cc"
bright_yellow = "#dc8a78"
brown = "#dd7878"
cyan = "#179299"
green = "#40a02b"
magenta = "#8839ef"
orange = "#fe640b"
red = "#d20f39"
white = "#acb0be"
yellow = "#df8e1d"
