name = "catppuccin-frappe"
description = "Imported base scheme: Catppuccin Frappe (dark)"

[colors]
black = "#51576d"
blue = "#8caaee"
bright_black = "#626880"
bright_blue = "#85c1dc"
bright_cyan = "#99d1db"
bright_green = "#a6d189"
bright_magenta = "#f4b8e4"
bright_red = "#ea999c"
bright_white = "#b5bfe2"
bright_yellow = "#f2d5cf"
brown = "#eebebe"
cyan = "#81c8be"
green = "#a6d189"
magenta = "#ca9ee6"
orange = "#ef9f76"
red = "#e78284"
white = "#a5adce"
yellow = "#e5c890"
