name = "catppuccin-mocha"
description = "Imported base scheme: Catppuccin Mocha (dark)"

[colors]
black = "#45475a"
blue = "#89b4fa"
bright_black = "#585b70"
bright_blue = "#74c7ec"
bright_cyan = "#89dceb"
bright_green = "#a6e3a1"
bright_magenta = "#f5c2e7"
bright_red = "#eba0ac"
bright_white = "#bac2de"
bright_yellow = "#f5e0dc"
brown = "#f2cdcd"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#cba6f7"
orange = "#fab387"
red = "#f38ba8"
white = "#a6adc8"
yellow = "#f9e2af"
