name = "gruvbox-dark-medium"
description = "Imported base scheme: Gruvbox dark, medium (dark)"

[colors]
black = "#282828"
blue = "#83a598"
bright_black = "#665c54"
bright_blue = "#83a598"
bright_cyan = "#8ec07c"
bright_green = "#b8bb26"
bright_magenta = "#d3869b"
bright_red = "#fb4934"
bright_white = "#fbf1c7"
bright_yellow = "#fabd2f"
brown = "#d65d0e"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
orange = "#fe8019"
red = "#fb4934"
white = "#d5c4a1"
yellow = "#fabd2f"
