name = "nord"
description = "Imported base scheme: Nord (dark)"

[colors]
black = "#2e3440"
blue = "#81a1c1"
bright_black = "#4c566a"
bright_blue = "#81a1c1"
bright_cyan = "#88c0d0"
bright_green = "#a3be8c"
bright_magenta = "#b48ead"
bright_red = "#bf616a"
bright_white = "#8fbcbb"
bright_yellow = "#ebcb8b"
brown = "#5e81ac"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
orange = "#d08770"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"
